#!/bin/bash
sudo add-apt-repository universe && sudo apt update
sudo apt-get install python python-dev python-all python3-pip python-all-dev libsasl2-dev libldap2-dev libssl-dev libxml2-dev libxslt-dev
sudo pip3 install python-ldap lxml
wget http://nightly.odoo.com/11.0/nightly/deb/odoo_11.0.20171003_all.deb
wget https://raw.githubusercontent.com/odoo/odoo/11.0/requirements.txt
pip3 install -r requirements.txt
sudo apt-get install ./odoo_11.0.20171003_all.deb
service odoo start
